### ISSUE TITLE
MGS2 HUD

### ISSUE THREAD

**Issue by Reonu** [Sergeanur/MGSResolutionPatch#1]
Hi! First of all thanks for this.

Are you planning to resolve the HUD issues with MGS2 or is that out of the scope of the project?

Also might I ask what the warning about resolutions other than 1080p and 2160p possibly not working is about? MGS3 seems to be fine at 2560x1440. 

Thanks!

**Comment by Sergeanur** [comment]
I wanna look into why some hud elements in MGS 2 don't scale, if it's not too much work I will patch it.

Good to know that 1440p works, I'll add that to readme.

**Comment by Sergeanur** [comment]
Fixed in plugin version 1.01
