### ISSUE TITLE
How does this fix compare to MGSHDFix?

### ISSUE THREAD

**Issue by Darthagnon** [Sergeanur/MGSResolutionPatch#10]
[MGSHDFix](https://github.com/Lyall/MGSHDFix) is another project that aims to do the same thing as this one. I was wondering which is better, or if there were any key differences? It is also recommended by PCGamingWiki.

Related issues: 
https://github.com/Lyall/MGSHDFix/issues/9

**Comment by Sergeanur** [comment]
The other mod does more so stick with that one I guess. Personally I don't feel like fixing everything wrong while Konami still has a team on a payroll for a post-launch support.

**Comment by Sergeanur** [comment]
Actually, now I pushed the fix for MGS 2 UI that fixes codec calls too, so there's a difference for ya. The other things like windowed, cursor, fancy aspect ratio stuff I don't have.
