### ISSUE TITLE
MGS 2 Visual

### ISSUE THREAD

**Issue by TerrorThrills** [Sergeanur/MGSResolutionPatch#3]
You probably already know this. But in case you are considering a version for MGS 2 Resolution . I've been looking into this for a while. It appears there's a layer that sits over the main visuals but under the Subtitles. This is rendering in 720p still hence the visual glitches.

This is used for lightning flashes, Fade In/out between scenes, codec calls (layer used for a distortion effect) and black upper and lower bars during certain cut scenes. They appear to be all on the same layer so likely have the same setting.

If you can find that setting then it should resolve the issue.

If not then thanks for all the work you put in. MGS 3 looks superb! 

![2131640_20231024233225_1](https://github.com/Sergeanur/MGSResolutionPatch/assets/137555995/f812a0c6-ec2c-44c6-bf40-e32f6fa53c21)
![2131640_20231025043815_1](https://github.com/Sergeanur/MGSResolutionPatch/assets/137555995/c919141c-712b-4f8e-b356-6b6123573e4a)

**Comment by TheSangral** [comment]
Yes I agree, playing a bit with it it also shows the game over screen, as well as the glass shatter effect when you die to get only displayed at the top left corner.

So perhaps there is just a few values left at 720p that he missed?

**Comment by Sergeanur** [comment]
Fixed in plugin version 1.01
